apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment-config.name: httpd-ex
    openshift.io/deployment.name: httpd-ex-1
    openshift.io/scc: restricted
  creationTimestamp: '2019-07-17T19:13:46Z'
  generateName: httpd-ex-1-
  labels:
    app: httpd-ex
    deployment: httpd-ex-1
    deploymentconfig: httpd-ex
  name: httpd-ex-1-djvqj
  namespace: myproject
  ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: httpd-ex-1
      uid: fd7e7c28-a8c6-11e9-95f3-ecf4bbf8a8db
  resourceVersion: '492475'
  selfLink: /api/v1/namespaces/myproject/pods/httpd-ex-1-djvqj
  uid: ffe6bd2d-a8c6-11e9-95f3-ecf4bbf8a8db
spec:
  containers:
    - image: >-
        172.30.1.1:5000/myproject/httpd-ex@sha256:e8064c44ba5dbe6a7a70549400fcd3cab615a495478a923a032c9b904ad284c0
      imagePullPolicy: Always
      name: httpd-ex
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1000140000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-96qkm
          readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: default-dockercfg-tzjrt
  nodeName: localhost
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000140000
    seLinuxOptions:
      level: 's0:c12,c4'
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
    - name: default-token-96qkm
      secret:
        defaultMode: 420
        secretName: default-token-96qkm
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2019-07-17T19:13:46Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2019-07-17T19:13:48Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      status: 'True'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2019-07-17T19:13:46Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        docker://978ab08c1c785bddbb3980eaed61ec8afca4dc0ddfd742f1050c489203313bd2
      image: '172.30.1.1:5000/myproject/httpd-ex:latest'
      imageID: >-
        docker-pullable://172.30.1.1:5000/myproject/httpd-ex@sha256:e8064c44ba5dbe6a7a70549400fcd3cab615a495478a923a032c9b904ad284c0
      lastState: {}
      name: httpd-ex
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: '2019-07-17T19:13:48Z'
  hostIP: 192.168.0.116
  phase: Running
  podIP: 172.17.0.6
  qosClass: BestEffort
  startTime: '2019-07-17T19:13:46Z'
